### PR TITLE
Add Symfony serializer support

### PR DESCRIPTION
**Pull request by polc**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

For people not using JSM serializer.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Looks good, thanks!

**Comment by xabbuh** [comment]
You may want to add a dev requirement on `symfony/serializer` to be sure to test this normaliser.

**Comment by thewilkybarkid** [comment]
Indeed. Will try and add one soon, but if someone could do a PR sooner even better.

**Comment by xabbuh** [comment]
@thewilkybarkid see #113

**Pull request merged**
