### PR TITLE
composer require instead of update

### PR DESCRIPTION
**Pull request by rvanlaak**
... so other libraries aren't updated

### CODE REVIEW

**Comment by Rvanlaak** [comment]
ping @thewilkybarkid

**Comment by Rvanlaak** [comment]
ping @thewilkybarkid

**Comment by rvanlaak** [comment]
ping @thewilkybarkid

**Comment by thewilkybarkid** [comment]
Sorry for the delay on this. I suggest we go for just `composer require misd/phone-number-bundle` as it's simpler (and Composer puts in the version constraint these days).

**Comment by thewilkybarkid** [comment]
Thanks, but I've implemented it in 8b937133f647a5acc2f0d00f4ad5bc221122011a.

**Comment by rvanlaak** [comment]
:+1:

**Pull request closed without merging**
