### PR TITLE
#158 - Changing the way it references twig templates

### PR DESCRIPTION
**Pull request by c0ntax**
Well, this hasn't broken any tests, so I assume that this fix works. ;-)

### CODE REVIEW

**Comment by giovkanata** [comment]
@kosdfol there is something to do before merge this?

**Comment by rh389** [comment]
I’ve lost touch with Symfony these days - can anyone point to docs / offer an explanation as to why this works? Is it backward compatible?

**Comment by odolbeau** [comment]
According to the documentation for symfony 3.4 [here](https://symfony.com/doc/3.4/templating/namespaced_paths.html), using semi colons is the old syntax and is not recommended anymore. I guess it have been removed in sf4.

**Comment by rh389** [comment]
Looks good, and the “new way” is documented back at least as far back as 2.7 so no BC issue. Merging! Thanks :)

**Pull request merged**
