### PR TITLE
Added getBlockPrefix to avoid deprecation in SF2.8

### PR DESCRIPTION
**Pull request by boekkooi**

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by m2mtech** [comment]
:+1:

**Comment by mbabker** [comment]
Can this be merged please?  This is the last dependency in my project blocking a Symfony 3 upgrade.

**Comment by boekkooi** [comment]
ping @thewilkybarkid

**Comment by giovkanata** [comment]
+1:

**Comment by thewilkybarkid** [comment]
@boekkooi Can you add a test case for this? I've haven't tried what happens, but @mbabker is suggesting there's a problem without it.

**Comment by boekkooi** [comment]
@thewilkybarkid Well the only real test that can be added is adding Symfony 3 to travis since it's only a deprecating warning fix would you like me to transform this PR into one where Symfony 3 is supported?

**Comment by thewilkybarkid** [comment]
Making sure those two methods returns `tel` should be enough.

**Comment by mbabker** [comment]
It's not a problem per se unless you're overriding the layout in Twig (the block name would be `phone_number` without this method instead of the currently defined `tel`).

**Comment by boekkooi** [comment]
@thewilkybarkid the test is added.
@mbabker I'm not sure if you are correct since [block_prefixes](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Form/Extension/Core/Type/BaseType.php#L65) and [unique_block_prefix](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Form/Extension/Core/Type/BaseType.php#L75) used the name on SF 2.3

**Comment by mbabker** [comment]
I'm going off the notes in the [2.8 upgrade guide](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md)

**Comment by boekkooi** [comment]
@mbabker 2.8 still uses [getName](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Extension/Core/Type/BaseType.php#L87) as a fallback for [getBlockPrefix](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Extension/Core/Type/BaseType.php#L87) so this PR creates no problems. Also see the upgrade guide: `If you want to create types that are compatible with Symfony 2.3 up to 2.8 and don't trigger deprecation errors, implement both getName() and getBlockPrefix():`

**Comment by mbabker** [comment]
Right, 2.8 is fine.  But in the off chance you need that behavior (honestly I hadn't fully read that part of the guide before today, I just saw a lot of projects doing it and was copying code before), if you don't have a `getBlockPrefix()` method in 3.0 then it causes a small B/C break.

**Comment by boekkooi** [comment]
@mbabker To and this PR avoids that BC break in the bundle

**Comment by thewilkybarkid** [comment]
Thanks!

**Comment by boekkooi** [comment]
@thewilkybarkid No problem thanks for merging

**Pull request merged**
