### PR TITLE
[Travis CI] Prefer Dist

### PR DESCRIPTION
**Pull request by JHGitty**
Reasons explained here: https://github.com/SURFnet/yubikey-api-client-bundle/pull/10

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: 

You can now also add Composer's file cache to the Travis CI cache.

**Comment by JHGitty** [comment]
@xabbuh Could you explain this, maybe with an example?

**Comment by xabbuh** [comment]
@JHGitty Just add these lines to the `.travis.yml` file:

```yaml
cache:
  directories:
    - $HOME/.composer/cache/files
```

**Comment by thewilkybarkid** [comment]
:+1: to adding caching too.

**Comment by xabbuh** [comment]
@JHGitty Can you make that change?

**Comment by thewilkybarkid** [comment]
Implemented in 845897f415fcba0018c180d667c1a6b03028d94c, thanks though.

**Comment by JHGitty** [comment]
@thewilkybarkid Please undo the change from ``--prefer-source`` to ``--prefer-dist``. The ``--prefer-source`` code is even better to prevent issues with rate limiting of Github: https://github.com/SURFnet/yubikey-api-client-bundle/pull/10#issuecomment-166866192

**Comment by xabbuh** [comment]
@JHGitty This shouldn't be true anymore as GitHub turned down their rate limiting for the file API recently.

**Pull request closed without merging**
