### PR TITLE
Create services only if dependency is available

### LINKED ISSUE #149: Symfony Flex compatibility
Specifically, check if Twig and/or Symfony Templating component is actually present.

There probably needs to be checks in place for the other components too...

### PR DESCRIPTION
**Pull request by ossinkine**
Closes #149 #168

### CODE REVIEW

**Comment by kmarques** [comment]
Any news about this PR?

I'm using this great bundle within my project. The point is that i'm using api-platform/api-platform and i don't need the templating engine.

**Comment by ossinkine** [comment]
@rh389 It seems you have no time to maintain this project. Maybe can you trust someone to maintain it?

**Comment by ossinkine** [comment]
@thewilkybarkid A lot of people using this project but unfortunately it is not maintaned properly. Could you entrust the maintaining of the project to a wider range of people?

**Comment by rh389** [comment]
LGTM, thanks

**Comment by teohhanhui** [comment]
This was merged into `master`. (Why? It's a bug.)

And there hasn't been a `1.4` release. So this is still not fixed as far as the users are concerned... :disappointed:

**Comment by ossinkine** [comment]
@teohhanhui Why is this a bug?

**Comment by teohhanhui** [comment]
@ossinkine Because the bundle breaks when `symfony/templating` is not installed, for example. And that's very much possible (and expected) beacuse `symfony/templating` is not in `require`.

**Comment by MlleDelphine** [comment]
@thewilkybarkid and @rh389 

Please, any action from your side to apply this PR to branch 1.3 please ?

**Pull request merged**
