### PR TITLE
Make addViolation protected

### PR DESCRIPTION
**Pull request by KathomDev**

### CODE REVIEW

**Comment by shakaran** [comment]
@rh389 This change seems suitable if you want extend or modify the validator, please check when you can for merge or decline, thanks!

**Comment by shakaran** [comment]
@rh389 BUMP ;)

**Comment by rh389** [comment]
I'm not sure about encouraging subclassing `PhoneNumberValidator`. See also discussion at https://github.com/misd-service-development/phone-number-bundle/issues/19

What's the use case for this?

**Comment by rh389** [comment]
Since we now use `buildViolation` when available I believe this is unnecessary

**Pull request closed without merging**
