### PR TITLE
Allow to validate phone number over multiple types.

### PR DESCRIPTION
**Pull request by ekyna**
Should be non breaking, please review.

### CODE REVIEW

**Comment by TZK-** [comment]
Is it planed to merge this ? It would be great if we could validate a field with multiple phone types (VOIP & Fixed Line for example)

**Comment by VincentLanglet** [comment]
This would be great

**Comment by camillebaronnet** [comment]
+1

**Comment by ekyna** [comment]
Closing as merged in maintained fork.
See [odolbeau/phone-number-bundle](https://github.com/odolbeau/phone-number-bundle/pull/24).

**Pull request closed without merging**
